services:
  webtorrent-mongodb-dev:
    container_name: webtorrent-mongodb-dev
    image: mongo
    restart: unless-stopped
    env_file:
      - mongo.env
    ports:
      - 27019:27017
    volumes:
      - ./database/webtorrent:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - webtorrent

  webtorrent-api-dev:
    container_name: webtorrent-api-dev
    build:
      context: ../WebTorrent.Api
    env_file:
      - api.env
    ports:
      - 5055:8800
    volumes:
      - ./tmp/torrent_downloads:/app/downloads
      - ./tmp/torrents:/app/torrents
      - ./data-protection-keys:/var/data-protection-keys
    depends_on:
      - webtorrent-mongodb-dev
    networks:
      - webtorrent

networks:
  webtorrent:
    driver: bridge